name: cli-jobs-pipelines-autom-mpg

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/4 * * *"
  pull_request:
    branches:
      - main
      - sdk-preview
    paths:
      - jobs/autompg_pipeline/**
      - .github/workflows/cli-jobs-pipelines-auto-mpg-pipeline.yml
      - run-jobs.sh
      - setup.sh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: azure login
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: setup
        run: bash setup.sh
        continue-on-error: true
      - name: run job
        run: bash -x ../../run-job.sh pipeline.yml
        working-directory: jobs/autompg_pipeline
